### ISSUE TITLE
Which paper does this code correspond to?

### ISSUE THREAD

**Issue by zhgqcn** [LeoVogiatzis/GNN_based_NILM#1]

**Comment by xinglongwang1** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/leonidas/PycharmProjects/GNN_based_NILM/data/House.csv'

**Comment by xinglongwang1** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/leonidas/PycharmProjects/GNN_based_NILM/data/House.csv'
请问house.csv是什么文件，redd数据集里面并没有这个文件
